---
name: CI Pipeline

on: push  # yamllint disable-line rule:truthy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Lint the project
        run: npm run lint
      - name: Build the project
        run: npm run build
      - name: List, audit, fix outdated dependencies and build again
        run: |
          npm list --outdated
          npm audit || true  # ignore failures
          npm audit fix || true
          npm list --outdated
          npm run build
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Generate documentation
        run: npm run docs
      - name: Upload generated documentation as github-pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html
  deploy_pages:
    runs-on: ubuntu-latest
    needs:
      - build
      - documentation
    if: (github.ref == 'refs/heads/master')
    concurrency:
      group: deploy-pages
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  publish_release:
    needs:
      - build
      - documentation
    if: (startsWith(github.ref, 'refs/tags/') && contains(github.ref, '.'))
    permissions:
      id-token: write  # Required for OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Publish package
        run: npm publish --access public
